apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-backup-network-policy
  namespace: prod
spec:
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: sre
        podSelector:
          matchLabels:
            app: nginx
    ports:
      - port: 5000
        protocol: TCP
  podSelector:
    matchLabels:
      name: app
  policyTypes:
  - Ingress
